"""
compare_search.py
=================
Compare Uniform Cost Search and A* across 10 randomised warehouse
configurations generated by WarehouseEnv.reset(randomize=True).

For each configuration:
  - Pickup (P) and dropoff (D) tiles are placed at random empty cells.
  - The robot starts at a random empty cell (distinct from P and D).

Both algorithms solve the same two-phase task:
  1. Navigate to the pickup tile and collect the item (PICK).
  2. Navigate to the dropoff tile and deliver the item (goal).

Output
------
  Console  : per-run log, optimality check, mean-statistics summary.
  Figure 1 : bar chart -- mean nodes expanded over 10 trials (UCS vs A*).
  Figure 2 : summary statistics table.
  Figure 3 : UCS animation -- grid + cumulative reward + distance graphs.
  Figure 4 : A* animation -- same graphs.
"""

from __future__ import annotations

from warehouse_env import WarehouseEnv
from ucs_pathfinder import uniform_cost_search, _initial_state, _get_frames
from astar_pathfinder import astar_search
from warehouse_viz import replay_animation

NUM_CONFIGS = 10


# ---------------------------------------------------------------------------
# Core comparison logic
# ---------------------------------------------------------------------------


def _run_config(env: WarehouseEnv, run: int) -> dict:
    """Run both searches on the current env state; return a result dict."""
    pickup_pos = env._find_tile("P")
    dropoff_pos = env._find_tile("D")
    start = env.start_pos

    ucs_path, ucs_stats = uniform_cost_search(env)
    astar_path, astar_stats = astar_search(env)

    ucs_solved = ucs_path is not None
    astar_solved = astar_path is not None
    lengths_match = (
        ucs_solved
        and astar_solved
        and ucs_stats["path_length"] == astar_stats["path_length"]
    )

    return {
        "run": run,
        "start": start,
        "pickup": pickup_pos,
        "dropoff": dropoff_pos,
        # UCS
        "ucs_nodes": ucs_stats["nodes_expanded"],
        "ucs_length": ucs_stats["path_length"],
        "ucs_frontier": ucs_stats["max_frontier_size"],
        "ucs_time": ucs_stats["computation_time"],
        "ucs_solved": ucs_solved,
        # A*
        "astar_nodes": astar_stats["nodes_expanded"],
        "astar_length": astar_stats["path_length"],
        "astar_frontier": astar_stats["max_frontier_size"],
        "astar_time": astar_stats["computation_time"],
        "astar_solved": astar_solved,
        # Optimality
        "optimal_match": lengths_match,
    }


# ---------------------------------------------------------------------------
# Metrics for animation
# ---------------------------------------------------------------------------


def _manhattan(a: tuple, b: tuple) -> int:
    return abs(a[0] - b[0]) + abs(a[1] - b[1])


def _compute_path_metrics(
    path: list,
    initial: tuple,
    pickup_pos: tuple,
    dropoff_pos: tuple,
) -> dict:
    """
    Build per-frame metric lists for replay_animation().

    rewards      : cumulative reward at each frame
                   (PICK earns +4.9, each move costs -0.1)
    dist_pickup  : Manhattan distance from robot to P at each frame
    dist_dropoff : Manhattan distance from robot to D at each frame
    """
    cumulative = 0.0
    rewards = []
    dist_pickup = []
    dist_dropoff = []

    r0, c0, _ = initial
    rewards.append(0.0)
    dist_pickup.append(_manhattan((r0, c0), pickup_pos))
    dist_dropoff.append(_manhattan((r0, c0), dropoff_pos))

    for action, state in path:
        r, c, _ = state
        cumulative += 4.9 if action == "PICK" else -0.1
        rewards.append(round(cumulative, 4))
        dist_pickup.append(_manhattan((r, c), pickup_pos))
        dist_dropoff.append(_manhattan((r, c), dropoff_pos))

    return {
        "rewards": rewards,
        "dist_pickup": dist_pickup,
        "dist_dropoff": dist_dropoff,
    }


# ---------------------------------------------------------------------------
# Console output helpers
# ---------------------------------------------------------------------------


def _fmt(pos) -> str:
    return f"({pos[0]},{pos[1]})" if pos else "None"


def _print_layout(grid: list[str]) -> None:
    for line in grid:
        print("  " + line)


def _print_run_log(results: list[dict]) -> None:
    """Per-run table: path length, nodes expanded, frontier size, time."""
    w = dict(run=3, pos=7, nodes=7, length=6, front=7, ms=8, match=6)
    hdr = (
        f"{'Run':>{w['run']}}  "
        f"{'Start':<{w['pos']}}  {'Pickup':<{w['pos']}}  {'Dropoff':<{w['pos']}}  "
        f"{'UCS-N':>{w['nodes']}}  {'UCS-L':>{w['length']}}  "
        f"{'UCS-Fr':>{w['front']}}  {'UCS-ms':>{w['ms']}}  "
        f"{'A*-N':>{w['nodes']}}  {'A*-L':>{w['length']}}  "
        f"{'A*-Fr':>{w['front']}}  {'A*-ms':>{w['ms']}}  "
        f"{'Optim?':>{w['match']}}"
    )
    print(hdr)
    print("-" * len(hdr))

    for r in results:
        us, as_ = r["ucs_solved"], r["astar_solved"]

        def _v(key, solved):
            return str(r[key]) if solved else "FAIL"

        ucs_ms_s = f"{r['ucs_time'] * 1000:.3f}" if us else "FAIL"
        astar_ms_s = f"{r['astar_time'] * 1000:.3f}" if as_ else "FAIL"

        print(
            f"{r['run']:>{w['run']}}  "
            f"{_fmt(r['start']):<{w['pos']}}  "
            f"{_fmt(r['pickup']):<{w['pos']}}  "
            f"{_fmt(r['dropoff']):<{w['pos']}}  "
            f"{_v('ucs_nodes', us):>{w['nodes']}}  "
            f"{_v('ucs_length', us):>{w['length']}}  "
            f"{_v('ucs_frontier', us):>{w['front']}}  "
            f"{ucs_ms_s:>{w['ms']}}  "
            f"{_v('astar_nodes', as_):>{w['nodes']}}  "
            f"{_v('astar_length', as_):>{w['length']}}  "
            f"{_v('astar_frontier', as_):>{w['front']}}  "
            f"{astar_ms_s:>{w['ms']}}  "
            f"{'YES' if r['optimal_match'] else 'NO':>{w['match']}}"
        )


def _print_optimality_check(results: list[dict]) -> None:
    solved_both = [r for r in results if r["ucs_solved"] and r["astar_solved"]]
    failures = [r for r in solved_both if not r["optimal_match"]]
    print()
    print("Optimality check")
    print("-" * 42)
    print(f"  Configs solved by both : {len(solved_both)}/{len(results)}")
    if failures:
        print(f"  PATH LENGTH MISMATCH in {len(failures)} run(s):")
        for r in failures:
            print(f"    Run {r['run']}: UCS={r['ucs_length']}  A*={r['astar_length']}")
    else:
        print("  All path lengths identical -- both algorithms are optimal.")


def _print_summary(results: list[dict]) -> None:
    """Print mean statistics across all solved configurations."""
    solved = [r for r in results if r["ucs_solved"] and r["astar_solved"]]
    n = len(solved)
    print()
    print(f"Mean statistics  ({n}/{len(results)} configs solved by both):")
    print("-" * 62)
    if n == 0:
        print("  Nothing to aggregate.")
        return

    def avg(key):
        return sum(r[key] for r in solved) / n

    mu_ucs_n = avg("ucs_nodes")
    mu_as_n = avg("astar_nodes")
    mu_ucs_l = avg("ucs_length")
    mu_as_l = avg("astar_length")
    mu_ucs_fr = avg("ucs_frontier")
    mu_as_fr = avg("astar_frontier")
    mu_ucs_ms = avg("ucs_time") * 1000
    mu_as_ms = avg("astar_time") * 1000
    node_savings = (mu_ucs_n - mu_as_n) / mu_ucs_n * 100 if mu_ucs_n else 0.0

    print(f"  {'Metric':<22}  {'UCS':>10}  {'A*':>10}  {'A* saves':>10}")
    print(f"  {'-' * 22}  {'-' * 10}  {'-' * 10}  {'-' * 10}")
    print(
        f"  {'Nodes expanded':<22}  {mu_ucs_n:>10.1f}  {mu_as_n:>10.1f}  {node_savings:>9.1f}%"
    )
    print(f"  {'Path length':<22}  {mu_ucs_l:>10.1f}  {mu_as_l:>10.1f}  {'(same)':>10}")
    print(f"  {'Max frontier size':<22}  {mu_ucs_fr:>10.1f}  {mu_as_fr:>10.1f}")
    print(f"  {'Time (ms)':<22}  {mu_ucs_ms:>10.4f}  {mu_as_ms:>10.4f}")


# ---------------------------------------------------------------------------
# Visualisations
# ---------------------------------------------------------------------------


def _make_bar_chart(results: list[dict]) -> None:
    """
    Two-bar chart: mean nodes expanded (UCS vs A*).
    Individual trial values overlaid as scatter points.
    """
    try:
        import matplotlib.pyplot as plt
        import numpy as np
    except ImportError:
        print("matplotlib/numpy not available; skipping bar chart.")
        return

    solved = [r for r in results if r["ucs_solved"] and r["astar_solved"]]
    if not solved:
        return

    ucs_vals = [r["ucs_nodes"] for r in solved]
    astar_vals = [r["astar_nodes"] for r in solved]

    mean_ucs = sum(ucs_vals) / len(ucs_vals)
    mean_as = sum(astar_vals) / len(astar_vals)
    std_ucs = (sum((v - mean_ucs) ** 2 for v in ucs_vals) / len(ucs_vals)) ** 0.5
    std_as = (sum((v - mean_as) ** 2 for v in astar_vals) / len(astar_vals)) ** 0.5

    fig, ax = plt.subplots(figsize=(6, 5))
    x = np.array([0, 1])
    colors = ["#4C72B0", "#DD8452"]
    means = [mean_ucs, mean_as]
    stds = [std_ucs, std_as]

    bars = ax.bar(
        x,
        means,
        width=0.45,
        color=colors,
        edgecolor="white",
        yerr=stds,
        capsize=6,
        error_kw={"elinewidth": 1.5},
    )

    for bar, mu in zip(bars, means):
        ax.text(
            bar.get_x() + bar.get_width() / 2,
            bar.get_height() + max(stds) * 0.15,
            f"{mu:.1f}",
            ha="center",
            va="bottom",
            fontsize=11,
            fontweight="bold",
        )

    jitter = np.linspace(-0.12, 0.12, len(solved))
    for xi, vals in zip(x, [ucs_vals, astar_vals]):
        ax.scatter(
            xi + jitter,
            vals,
            color="black",
            s=28,
            zorder=5,
            alpha=0.7,
            label="Individual trial" if xi == x[0] else "",
        )

    ax.set_xticks(x)
    ax.set_xticklabels(["UCS", "A*"], fontsize=13)
    ax.set_ylabel("Nodes Expanded", fontsize=11)
    ax.set_title(
        f"Mean Nodes Expanded over {len(solved)} Trials\n"
        "(error bars = std dev,  dots = individual trials)",
        fontsize=11,
    )
    ax.legend(fontsize=9)
    ax.set_ylim(0, max(max(ucs_vals), max(astar_vals)) * 1.3)
    ax.grid(axis="y", alpha=0.3)
    fig.tight_layout()
    plt.show()


def _make_summary_table(results: list[dict]) -> None:
    """Summary statistics rendered as a matplotlib table."""
    try:
        import matplotlib.pyplot as plt
    except ImportError:
        print("matplotlib not available; skipping summary table.")
        return

    solved = [r for r in results if r["ucs_solved"] and r["astar_solved"]]
    n = len(solved)
    if n == 0:
        return

    def avg(key):
        return sum(r[key] for r in solved) / n

    def std(key):
        mu = avg(key)
        return (sum((r[key] - mu) ** 2 for r in solved) / n) ** 0.5

    metrics_def = [
        ("Nodes expanded", "ucs_nodes", "astar_nodes", 1.0),
        ("Path length", "ucs_length", "astar_length", 1.0),
        ("Max frontier size", "ucs_frontier", "astar_frontier", 1.0),
        ("Time (ms)", "ucs_time", "astar_time", 1000.0),
    ]

    cells = []
    for label, uk, ak, scale in metrics_def:
        ua, us_ = avg(uk) * scale, std(uk) * scale
        aa, as_ = avg(ak) * scale, std(ak) * scale
        diff = (
            "same"
            if label == "Path length"
            else (f"{(ua - aa) / ua * 100:+.1f}%" if ua else "n/a")
        )
        cells.append(
            [label, f"{ua:.2f} +/- {us_:.2f}", f"{aa:.2f} +/- {as_:.2f}", diff]
        )

    col_labels = ["Metric", "UCS  (mean +/- std)", "A*  (mean +/- std)", "A* vs UCS"]

    fig, ax = plt.subplots(figsize=(10, 2.6))
    ax.set_axis_off()
    tbl = ax.table(cellText=cells, colLabels=col_labels, cellLoc="center", loc="center")
    tbl.auto_set_font_size(False)
    tbl.set_fontsize(10)

    for j in range(len(col_labels)):
        tbl[0, j].set_facecolor("#2C3E50")
        tbl[0, j].set_text_props(color="white", fontweight="bold")
    for i in range(1, len(cells) + 1):
        bg = "#EAF2FB" if i % 2 == 0 else "#FDFEFE"
        for j in range(len(col_labels)):
            tbl[i, j].set_facecolor(bg)

    tbl.auto_set_column_width(list(range(len(col_labels))))
    all_match = all(r["optimal_match"] for r in solved)
    note = (
        "Optimality: all path lengths agree."
        if all_match
        else "WARNING: path length mismatch!"
    )
    fig.suptitle(
        f"UCS vs A*: Summary Statistics  ({n}/{len(results)} trials solved)",
        fontsize=12,
        fontweight="bold",
        y=0.98,
    )
    fig.text(
        0.5, 0.01, note, ha="center", fontsize=9, color="green" if all_match else "red"
    )
    fig.tight_layout(rect=[0, 0.05, 1, 0.93])
    plt.show()


def _show_animation(env: WarehouseEnv, path: list, algo_name: str) -> None:
    """Show an animated solution with cumulative-reward and distance graphs."""
    initial = _initial_state(env)
    frames = _get_frames(env, path, initial)
    pickup_pos = env._find_tile("P")
    dropoff_pos = env._find_tile("D")
    metrics = _compute_path_metrics(path, initial, pickup_pos, dropoff_pos)

    print(
        f"\n{algo_name} animation  ({len(path)} steps)  -- close window to continue..."
    )
    replay_animation(frames, metrics=metrics, interval_ms=300)


# ---------------------------------------------------------------------------
# Entry point
# ---------------------------------------------------------------------------


def compare(num_configs: int = NUM_CONFIGS) -> list[dict]:
    env = WarehouseEnv()

    print("=" * 72)
    print("  UCS vs A*  -  Warehouse Search Comparison")
    print("=" * 72)
    print("\nDefault warehouse layout (walls fixed; P/D randomised each trial):")
    _print_layout(env.grid)
    print(f"\nRunning {num_configs} random trials via reset(randomize=True)...\n")

    results = []
    for run in range(1, num_configs + 1):
        env.reset(randomize=True)
        env.start_pos = env.state.robot_pos  # sync randomised start
        results.append(_run_config(env, run))

    # Console output
    _print_run_log(results)
    _print_optimality_check(results)
    _print_summary(results)

    # Static visualisations
    print("\nGenerating visualisations...")
    _make_bar_chart(results)
    _make_summary_table(results)

    # Animations on the default (non-randomised) layout
    print("\nRunning UCS and A* on the default layout for animation...")
    demo_env = WarehouseEnv()

    ucs_path, _ = uniform_cost_search(demo_env)
    astar_path, _ = astar_search(demo_env)

    if ucs_path:
        _show_animation(demo_env, ucs_path, "UCS")
    else:
        print("UCS: no solution found on default layout.")

    if astar_path:
        _show_animation(demo_env, astar_path, "A*")
    else:
        print("A*: no solution found on default layout.")

    return results


if __name__ == "__main__":
    compare()
